---
- name: Init cluster | Check if kubeadm has already run
  stat:
    path: "/etc/kubernetes/pki/ca.crt"
  register: kubeadm_already_run
  run_once: yes

- block:
  - name: Update kubelet configuration
    template:
      src: templates/kubelet.j2
      dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
  
  - name: Reload kubelet configuration
    systemd:
      state: restarted
      daemon_reload: yes
      name: kubelet
  
  - name: Copy the join command to server location
    copy: src=/tmp/join-command dest=/tmp/join-command.sh mode=0700
  
  - name: Join the node to cluster
    become: yes
    command: sh /tmp/join-command.sh

  when:
  - not kubeadm_already_run.stat.exists
  run_once: yes
