apiVersion: apps/v1
kind: Deployment
metadata:
  name: epoch-converter-deployment
  labels:
    k8s-app: epoch-converter
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: epoch-converter
  template:
    metadata:
      labels:
        k8s-app: epoch-converter
    spec:
      containers:
      - name: epoch-converter
        image: parsayousefi97/evl-converter:0.0.1
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: PRODUCER_BROKERS
          value: "kafka-epoch-kafka-brokers:9092"
        - name: PRODUCER_TOPIC
          value: "output"
        - name: PRODUCER_VERSION
          value: "2.7.0"
        - name: CONSUMER_BROKERS
          value: "kafka-epoch-kafka-brokers:9092"
        - name: CONSUMER_TOPIC
          value: "input"
        - name: CONSUMER_VERSION
          value: "2.7.0"
        ports:
        - containerPort: 8081
          name: metrics
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: epoch-converter-metrics
  labels:
    k8s-app: epoch-converter
  annotations:
    prometheus.io/port: "8081"
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    k8s-app: epoch-converter
