apiVersion: apps/v1
kind: Deployment
metadata:
  name: epoch-producer-deployment
  labels:
    k8s-app: epoch-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: epoch-producer
  template:
    metadata:
      labels:
        k8s-app: epoch-producer
    spec:
      containers:
      - name: epoch-producer
        image: parsayousefi97/evl-producer:0.0.1
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: PRODUCER_BROKERS
          value: "kafka-epoch-kafka-brokers:9092"
        - name: TOPIC
          value: "input"
        - name: PRODUCER_VERSION
          value: "2.7.0"
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: epoch-producer-metrics
  labels:
    k8s-app: epoch-producer
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    k8s-app: epoch-producer
