---
- name: Install containerd
  apt:
    name: containerd=1.3.3-0ubuntu2
    update_cache: yes

- name: Install docker
  apt:
    name: docker.io=19.03.8-0ubuntu1.20.04.1
    update_cache: yes

- name: Create the docker group
  group:
    name: docker

- name: Add vagrant user to the docker group
  user:
    name: vagrant
    groups: docker
    append: yes

- name: Start docker
  systemd:
    name: docker
    state: started
    enabled: yes
